// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
void ui_event_DDS1_Dec_button_1(lv_event_t * e);
lv_obj_t * ui_DDS1_Dec_button_1;
lv_obj_t * ui_Label11;
void ui_event_DDS1_Add_button_1(lv_event_t * e);
lv_obj_t * ui_DDS1_Add_button_1;
lv_obj_t * ui_Label12;
void ui_event_DDS1_calibrate_Spinbox_1(lv_event_t * e);
lv_obj_t * ui_DDS1_calibrate_Spinbox_1;
void ui_event_DDS1_Fre_Spinbox_1(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Spinbox_1;
void ui_event_DDS1_Fre_Add_button_1(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Add_button_1;
lv_obj_t * ui_Label9;
void ui_event_DDS1_Fre_Dec_button_1(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Dec_button_1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label18;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
void ui_event_DDS1_Dec_button1(lv_event_t * e);
lv_obj_t * ui_DDS1_Dec_button1;
lv_obj_t * ui_Label13;
void ui_event_DDS1_Add_button1(lv_event_t * e);
lv_obj_t * ui_DDS1_Add_button1;
lv_obj_t * ui_Label14;
void ui_event_DDS1_calibrate_Spinbox_2(lv_event_t * e);
lv_obj_t * ui_DDS1_calibrate_Spinbox_2;
void ui_event_DDS1_Fre_Spinbox_2(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Spinbox_2;
void ui_event_DDS1_Fre_Add_button1(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Add_button1;
lv_obj_t * ui_Label15;
void ui_event_DDS1_Fre_Dec_button1(lv_event_t * e);
lv_obj_t * ui_DDS1_Fre_Dec_button1;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label17;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
        DDS1_Change(e);
    }
}
void ui_event_DDS1_Dec_button_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_calibrate_Spinbox_1, -1);
    }
}
void ui_event_DDS1_Add_button_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_calibrate_Spinbox_1, 1);
    }
}
void ui_event_DDS1_calibrate_Spinbox_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS1_Cal_Set(e);
    }
}
void ui_event_DDS1_Fre_Spinbox_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS1_Fre_Set(e);
    }
}
void ui_event_DDS1_Fre_Add_button_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_Fre_Spinbox_1, 1);
    }
}
void ui_event_DDS1_Fre_Dec_button_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_Fre_Spinbox_1, -1);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
        DDS2_Change(e);
    }
}
void ui_event_DDS1_Dec_button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_calibrate_Spinbox_2, -1);
    }
}
void ui_event_DDS1_Add_button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_calibrate_Spinbox_2, 1);
    }
}
void ui_event_DDS1_calibrate_Spinbox_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS2_Cal_Set(e);
    }
}
void ui_event_DDS1_Fre_Spinbox_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS2_Fre_Set(e);
    }
}
void ui_event_DDS1_Fre_Add_button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_Fre_Spinbox_2, 1);
    }
}
void ui_event_DDS1_Fre_Dec_button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_DDS1_Fre_Spinbox_2, -1);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
