// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_DDS1_Dec_button_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Dec_button_1;
extern lv_obj_t * ui_Label11;
void ui_event_DDS1_Add_button_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Add_button_1;
extern lv_obj_t * ui_Label12;
void ui_event_DDS1_calibrate_Spinbox_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_calibrate_Spinbox_1;
void ui_event_DDS1_Fre_Spinbox_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Spinbox_1;
void ui_event_DDS1_Fre_Add_button_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Add_button_1;
extern lv_obj_t * ui_Label9;
void ui_event_DDS1_Fre_Dec_button_1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Dec_button_1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label18;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_DDS1_Dec_button1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Dec_button1;
extern lv_obj_t * ui_Label13;
void ui_event_DDS1_Add_button1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Add_button1;
extern lv_obj_t * ui_Label14;
void ui_event_DDS1_calibrate_Spinbox_2(lv_event_t * e);
extern lv_obj_t * ui_DDS1_calibrate_Spinbox_2;
void ui_event_DDS1_Fre_Spinbox_2(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Spinbox_2;
void ui_event_DDS1_Fre_Add_button1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Add_button1;
extern lv_obj_t * ui_Label15;
void ui_event_DDS1_Fre_Dec_button1(lv_event_t * e);
extern lv_obj_t * ui_DDS1_Fre_Dec_button1;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
