// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DDS1_Change(lv_event_t * e);
void DDS1_Cal_Set(lv_event_t * e);
void DDS1_Fre_Set(lv_event_t * e);
void DDS2_Change(lv_event_t * e);
void DDS2_Cal_Set(lv_event_t * e);
void DDS2_Fre_Set(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
