// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"

extern double DDS1_Fre_1M; // 校准参数
extern double DDS2_Fre_1M;

double DDS1_Fre = 10000.0;  // 设置频率
double DDS2_Fre = 10000.0;  // 设置频率

extern double Div_Fre1, Div_Fre2;
int32_t DDS1_Fre_temp, DDS1_Cal_temp;
int32_t DDS2_Fre_temp, DDS2_Cal_temp;

void DDS1_Cal_Set(lv_event_t * e)
{
	// Your code here
	double DDS1_Fre_test;
	DDS1_Cal_temp = lv_spinbox_get_value(ui_DDS1_calibrate_Spinbox_1);
	DDS1_Fre_1M = 1000000.0 + DDS1_Cal_temp/10000.0;
	DDS1_Fre_test = Div_Fre1 * DDS1_Fre_1M/1000000.0;
	AD9854_SetSine_double(DDS1_Fre_test, 4095);
	printf("DDS1_Cal:%f\r\n", DDS1_Fre_1M);
	printf("DDS1_Fre_test:%f\r\n", DDS1_Fre_test);
}

void DDS1_Fre_Set(lv_event_t * e)
{
	// Your code here
	DDS1_Fre_temp = lv_spinbox_get_value(ui_DDS1_Fre_Spinbox_1);
	DDS1_Fre = DDS1_Fre_temp*DDS1_Fre_1M/1000000.0*10;
	AD9854_SetSine_double(DDS1_Fre, 4095);
	printf("DDS1_Fre:%f\r\n", DDS1_Fre);
}

void DDS2_Cal_Set(lv_event_t * e)
{
	// Your code here
	double DDS2_Fre_test;
	DDS2_Cal_temp = lv_spinbox_get_value(ui_DDS1_calibrate_Spinbox_2);
	DDS2_Fre_1M = 1000000.0 + DDS2_Cal_temp/10000.0;
	DDS2_Fre_test = Div_Fre2 * DDS2_Fre_1M/1000000.0;
	AD9851_Setfq(DDS2_Fre_test);	
	printf("DDS2_Cal:%f\r\n", DDS2_Fre_1M);
	printf("DDS2_Fre_test:%f\r\n", DDS2_Fre_test);
}

void DDS2_Fre_Set(lv_event_t * e)
{
	// Your code here
	DDS2_Fre_temp = lv_spinbox_get_value(ui_DDS1_Fre_Spinbox_2);
	DDS2_Fre = DDS2_Fre_temp*DDS2_Fre_1M/1000000.0*10;
	AD9851_Setfq(DDS2_Fre);	
	printf("DDS2_Fre:%f\r\n", DDS2_Fre);
}

void DDS1_Change(lv_event_t * e)
{
	// Your code here
	
}

void DDS2_Change(lv_event_t * e)
{
	// Your code here
}
