// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void load_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_select;
lv_obj_t * ui_DAC;
lv_obj_t * ui_Wave_tab;
void ui_event_Wave_select(lv_event_t * e);
lv_obj_t * ui_Wave_select;
void ui_event_OUT_switch(lv_event_t * e);
lv_obj_t * ui_OUT_switch;
lv_obj_t * ui_OUT_tab;
lv_obj_t * ui_Fre_tab;
void ui_event_Fre(lv_event_t * e);
lv_obj_t * ui_Fre;
void ui_event_Fre_inc_btn(lv_event_t * e);
lv_obj_t * ui_Fre_inc_btn;
lv_obj_t * ui_Fre_inc_tab;
void ui_event_Fre_dec_btn(lv_event_t * e);
lv_obj_t * ui_Fre_dec_btn;
lv_obj_t * ui_Fre_dec_tab;
lv_obj_t * ui_Vol_tab;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_ADC;
lv_obj_t * ui_Label2;
void ui_event_measure(lv_event_t * e);
lv_obj_t * ui_measure;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void load_Animation(lv_obj_t * TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Wave_select(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DAC_Wave_set(e);
    }
}
void ui_event_OUT_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DAC_Output(e);
        _ui_checked_set_text_value(ui_OUT_tab, target, "OUT:ON", "OUT:OFF");
    }
}
void ui_event_Fre(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DAC_Fre_set(e);
    }
}
void ui_event_Fre_inc_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Fre, 1);
    }
}
void ui_event_Fre_dec_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Fre, -1);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DAC_Vol_set(e);
        _ui_slider_set_text_value(ui_Vol_tab, target, "Vol:", "%");
    }
}
void ui_event_measure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ADC_data_send(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
