// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DAC_Wave_set(lv_event_t * e);
void DAC_Output(lv_event_t * e);
void DAC_Fre_set(lv_event_t * e);
void DAC_Vol_set(lv_event_t * e);
void ADC_data_send(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
