// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#include "ui.h"

void DAC_Wave_set(lv_event_t * e)
{
	// Your code here
}

void DAC_Output(lv_event_t * e)
{
	// Your code here
}

void DAC_Fre_set(lv_event_t * e)
{
	// Your code here
}

void DAC_Vol_set(lv_event_t * e)
{
	// Your code here
}

void ADC_data_send(lv_event_t * e)
{
	// Your code here
}
