// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DDS1_Dec_button_1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_Dec_button_1, 60);
    lv_obj_set_height(ui_DDS1_Dec_button_1, 40);
    lv_obj_set_x(ui_DDS1_Dec_button_1, 57);
    lv_obj_set_y(ui_DDS1_Dec_button_1, 110);
    lv_obj_set_align(ui_DDS1_Dec_button_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Dec_button_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Dec_button_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_DDS1_Dec_button_1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "-");

    ui_DDS1_Add_button_1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_Add_button_1, 60);
    lv_obj_set_height(ui_DDS1_Add_button_1, 40);
    lv_obj_set_x(ui_DDS1_Add_button_1, -50);
    lv_obj_set_y(ui_DDS1_Add_button_1, 110);
    lv_obj_set_align(ui_DDS1_Add_button_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Add_button_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Add_button_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_DDS1_Add_button_1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "+");

    ui_DDS1_calibrate_Spinbox_1 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_calibrate_Spinbox_1, 100);
    lv_obj_set_height(ui_DDS1_calibrate_Spinbox_1, 40);
    lv_obj_set_x(ui_DDS1_calibrate_Spinbox_1, 0);
    lv_obj_set_y(ui_DDS1_calibrate_Spinbox_1, 60);
    lv_obj_set_align(ui_DDS1_calibrate_Spinbox_1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_DDS1_calibrate_Spinbox_1, 7, 3);
    lv_spinbox_set_range(ui_DDS1_calibrate_Spinbox_1, -9999999, 9999999);
    lv_spinbox_set_step(ui_DDS1_calibrate_Spinbox_1, round(pow(10, 1 - 1)));

    lv_obj_set_style_text_align(ui_DDS1_calibrate_Spinbox_1, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_DDS1_Fre_Spinbox_1 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_Fre_Spinbox_1, 90);
    lv_obj_set_height(ui_DDS1_Fre_Spinbox_1, 40);
    lv_obj_set_x(ui_DDS1_Fre_Spinbox_1, 0);
    lv_obj_set_y(ui_DDS1_Fre_Spinbox_1, -70);
    lv_obj_set_align(ui_DDS1_Fre_Spinbox_1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_DDS1_Fre_Spinbox_1, 6, 4);
    lv_spinbox_set_range(ui_DDS1_Fre_Spinbox_1, -999999, 999999);
    lv_spinbox_set_step(ui_DDS1_Fre_Spinbox_1, round(pow(10, 1 - 1)));

    ui_DDS1_Fre_Add_button_1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_Fre_Add_button_1, 60);
    lv_obj_set_height(ui_DDS1_Fre_Add_button_1, 40);
    lv_obj_set_x(ui_DDS1_Fre_Add_button_1, -50);
    lv_obj_set_y(ui_DDS1_Fre_Add_button_1, -10);
    lv_obj_set_align(ui_DDS1_Fre_Add_button_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Fre_Add_button_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Fre_Add_button_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_DDS1_Fre_Add_button_1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "+");

    ui_DDS1_Fre_Dec_button_1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_DDS1_Fre_Dec_button_1, 60);
    lv_obj_set_height(ui_DDS1_Fre_Dec_button_1, 40);
    lv_obj_set_x(ui_DDS1_Fre_Dec_button_1, 56);
    lv_obj_set_y(ui_DDS1_Fre_Dec_button_1, -10);
    lv_obj_set_align(ui_DDS1_Fre_Dec_button_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Fre_Dec_button_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Fre_Dec_button_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_DDS1_Fre_Dec_button_1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "-");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -85);
    lv_obj_set_y(ui_Label2, -70);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Fre");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 80);
    lv_obj_set_y(ui_Label3, -72);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "KHz");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -85);
    lv_obj_set_y(ui_Label4, 60);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Cal");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -120);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Output1");

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 80);
    lv_obj_set_y(ui_Label18, 60);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Hz");

    lv_obj_add_event_cb(ui_DDS1_Dec_button_1, ui_event_DDS1_Dec_button_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Add_button_1, ui_event_DDS1_Add_button_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_calibrate_Spinbox_1, ui_event_DDS1_calibrate_Spinbox_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Spinbox_1, ui_event_DDS1_Fre_Spinbox_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Add_button_1, ui_event_DDS1_Fre_Add_button_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Dec_button_1, ui_event_DDS1_Fre_Dec_button_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
