// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DDS1_Dec_button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_Dec_button1, 60);
    lv_obj_set_height(ui_DDS1_Dec_button1, 40);
    lv_obj_set_x(ui_DDS1_Dec_button1, 57);
    lv_obj_set_y(ui_DDS1_Dec_button1, 110);
    lv_obj_set_align(ui_DDS1_Dec_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Dec_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Dec_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_DDS1_Dec_button1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "-");

    ui_DDS1_Add_button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_Add_button1, 60);
    lv_obj_set_height(ui_DDS1_Add_button1, 40);
    lv_obj_set_x(ui_DDS1_Add_button1, -50);
    lv_obj_set_y(ui_DDS1_Add_button1, 110);
    lv_obj_set_align(ui_DDS1_Add_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Add_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Add_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_DDS1_Add_button1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "+");

    ui_DDS1_calibrate_Spinbox_2 = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_calibrate_Spinbox_2, 100);
    lv_obj_set_height(ui_DDS1_calibrate_Spinbox_2, 40);
    lv_obj_set_x(ui_DDS1_calibrate_Spinbox_2, 0);
    lv_obj_set_y(ui_DDS1_calibrate_Spinbox_2, 60);
    lv_obj_set_align(ui_DDS1_calibrate_Spinbox_2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_DDS1_calibrate_Spinbox_2, 7, 3);
    lv_spinbox_set_range(ui_DDS1_calibrate_Spinbox_2, -9999999, 9999999);
    lv_spinbox_set_step(ui_DDS1_calibrate_Spinbox_2, round(pow(10, 1 - 1)));

    lv_obj_set_style_text_align(ui_DDS1_calibrate_Spinbox_2, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_DDS1_Fre_Spinbox_2 = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_Fre_Spinbox_2, 90);
    lv_obj_set_height(ui_DDS1_Fre_Spinbox_2, 40);
    lv_obj_set_x(ui_DDS1_Fre_Spinbox_2, 0);
    lv_obj_set_y(ui_DDS1_Fre_Spinbox_2, -70);
    lv_obj_set_align(ui_DDS1_Fre_Spinbox_2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_DDS1_Fre_Spinbox_2, 6, 4);
    lv_spinbox_set_range(ui_DDS1_Fre_Spinbox_2, -999999, 999999);
    lv_spinbox_set_step(ui_DDS1_Fre_Spinbox_2, round(pow(10, 1 - 1)));

    ui_DDS1_Fre_Add_button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_Fre_Add_button1, 60);
    lv_obj_set_height(ui_DDS1_Fre_Add_button1, 40);
    lv_obj_set_x(ui_DDS1_Fre_Add_button1, -50);
    lv_obj_set_y(ui_DDS1_Fre_Add_button1, -10);
    lv_obj_set_align(ui_DDS1_Fre_Add_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Fre_Add_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Fre_Add_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_DDS1_Fre_Add_button1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "+");

    ui_DDS1_Fre_Dec_button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_DDS1_Fre_Dec_button1, 60);
    lv_obj_set_height(ui_DDS1_Fre_Dec_button1, 40);
    lv_obj_set_x(ui_DDS1_Fre_Dec_button1, 56);
    lv_obj_set_y(ui_DDS1_Fre_Dec_button1, -10);
    lv_obj_set_align(ui_DDS1_Fre_Dec_button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS1_Fre_Dec_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DDS1_Fre_Dec_button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_DDS1_Fre_Dec_button1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "-");

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -85);
    lv_obj_set_y(ui_Label1, -70);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Fre");

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 80);
    lv_obj_set_y(ui_Label5, -72);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "KHz");

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -85);
    lv_obj_set_y(ui_Label6, 60);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Cal");

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -120);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Output2");

    ui_Label17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 80);
    lv_obj_set_y(ui_Label17, 60);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Hz");

    lv_obj_add_event_cb(ui_DDS1_Dec_button1, ui_event_DDS1_Dec_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Add_button1, ui_event_DDS1_Add_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_calibrate_Spinbox_2, ui_event_DDS1_calibrate_Spinbox_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Spinbox_2, ui_event_DDS1_Fre_Spinbox_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Add_button1, ui_event_DDS1_Fre_Add_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS1_Fre_Dec_button1, ui_event_DDS1_Fre_Dec_button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
