// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void load_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_select;
lv_obj_t * ui_DDS;
lv_obj_t * ui_Fre_tag;
void ui_event_Fre_Value(lv_event_t * e);
lv_obj_t * ui_Fre_Value;
void ui_event_DDS_Fre_Range(lv_event_t * e);
lv_obj_t * ui_DDS_Fre_Range;
void ui_event_DDS_Vol_Slider(lv_event_t * e);
lv_obj_t * ui_DDS_Vol_Slider;
lv_obj_t * ui_DDS_Vol;
lv_obj_t * ui_DDS_Output_tag;
void ui_event_Fre_Value_Add(lv_event_t * e);
lv_obj_t * ui_Fre_Value_Add;
lv_obj_t * ui_add;
void ui_event_Fre_Value_Dec(lv_event_t * e);
lv_obj_t * ui_Fre_Value_Dec;
lv_obj_t * ui_dec;
void ui_event_Sweep_Switch(lv_event_t * e);
lv_obj_t * ui_Sweep_Switch;
lv_obj_t * ui_ADC;
void ui_event_Measure_Button(lv_event_t * e);
lv_obj_t * ui_Measure_Button;
lv_obj_t * ui_Measure_tag;
lv_obj_t * ui_Wave_Show;
lv_obj_t * ui_DAC;
lv_obj_t * ui_DAC_Value_tag;
void ui_event_DAC_Value_Set(lv_event_t * e);
lv_obj_t * ui_DAC_Value_Set;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void load_Animation(lv_obj_t * TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Fre_Value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS_FreValueSet(e);
    }
}
void ui_event_DDS_Fre_Range(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS_FreRangeSet(e);
    }
}
void ui_event_DDS_Vol_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS_OutputSet(e);
        _ui_slider_set_text_value(ui_DDS_Vol, target, "Vol:", "");
    }
}
void ui_event_Fre_Value_Add(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Fre_Value, 1);
    }
}
void ui_event_Fre_Value_Dec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Fre_Value, -1);
    }
}
void ui_event_Sweep_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DDS_Sweep(e);
    }
}
void ui_event_Measure_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        measure_FFT(e);
    }
}
void ui_event_DAC_Value_Set(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DAC_OutputSet(e);
        _ui_slider_set_text_value(ui_DAC_Value_tag, target, "DAC_Vol:", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
