// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#ifndef _MY_TEST_UI_H
#define _MY_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void load_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_select;
extern lv_obj_t * ui_DDS;
extern lv_obj_t * ui_Fre_tag;
void ui_event_Fre_Value(lv_event_t * e);
extern lv_obj_t * ui_Fre_Value;
void ui_event_DDS_Fre_Range(lv_event_t * e);
extern lv_obj_t * ui_DDS_Fre_Range;
void ui_event_DDS_Vol_Slider(lv_event_t * e);
extern lv_obj_t * ui_DDS_Vol_Slider;
extern lv_obj_t * ui_DDS_Vol;
extern lv_obj_t * ui_DDS_Output_tag;
void ui_event_Fre_Value_Add(lv_event_t * e);
extern lv_obj_t * ui_Fre_Value_Add;
extern lv_obj_t * ui_add;
void ui_event_Fre_Value_Dec(lv_event_t * e);
extern lv_obj_t * ui_Fre_Value_Dec;
extern lv_obj_t * ui_dec;
void ui_event_Sweep_Switch(lv_event_t * e);
extern lv_obj_t * ui_Sweep_Switch;
extern lv_obj_t * ui_ADC;
void ui_event_Measure_Button(lv_event_t * e);
extern lv_obj_t * ui_Measure_Button;
extern lv_obj_t * ui_Measure_tag;
extern lv_obj_t * ui_Wave_Show;
extern lv_obj_t * ui_DAC;
extern lv_obj_t * ui_DAC_Value_tag;
void ui_event_DAC_Value_Set(lv_event_t * e);
extern lv_obj_t * ui_DAC_Value_Set;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
