// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Screen_Button1, 59);
    lv_obj_set_height(ui_Screen_Button1, 33);
    lv_obj_set_x(ui_Screen_Button1, -73);
    lv_obj_set_y(ui_Screen_Button1, -99);
    lv_obj_set_align(ui_Screen_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinbox1 = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_Spinbox1, 92);
    lv_obj_set_height(ui_Spinbox1, 40);
    lv_obj_set_x(ui_Spinbox1, -59);
    lv_obj_set_y(ui_Spinbox1, -1);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 6, 2);
    lv_spinbox_set_range(ui_Spinbox1, -999999, 999999);
    lv_spinbox_set_step(ui_Spinbox1, round(pow(10, 1 - 1)));

    ui_Fre_Value_Add1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Fre_Value_Add1, 51);
    lv_obj_set_height(ui_Fre_Value_Add1, 39);
    lv_obj_set_x(ui_Fre_Value_Add1, 49);
    lv_obj_set_y(ui_Fre_Value_Add1, -41);
    lv_obj_set_align(ui_Fre_Value_Add1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fre_Value_Add1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fre_Value_Add1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_add1 = lv_label_create(ui_Fre_Value_Add1);
    lv_obj_set_width(ui_add1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_add1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_add1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_add1, "+");

    ui_Fre_Value_Dec1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Fre_Value_Dec1, 51);
    lv_obj_set_height(ui_Fre_Value_Dec1, 43);
    lv_obj_set_x(ui_Fre_Value_Dec1, 50);
    lv_obj_set_y(ui_Fre_Value_Dec1, 29);
    lv_obj_set_align(ui_Fre_Value_Dec1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fre_Value_Dec1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fre_Value_Dec1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dec1 = lv_label_create(ui_Fre_Value_Dec1);
    lv_obj_set_width(ui_dec1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dec1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dec1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dec1, "-");

    lv_obj_add_event_cb(ui_Screen_Button1, ui_event_Screen_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Spinbox1, ui_event_Spinbox1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fre_Value_Add1, ui_event_Fre_Value_Add1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fre_Value_Dec1, ui_event_Fre_Value_Dec1, LV_EVENT_ALL, NULL);

}
