// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_add_event_cb(ui_Screen1, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Screen1);

    ui_select = lv_tabview_create(ui_Screen1, LV_DIR_LEFT, 50);
    lv_obj_set_width(ui_select, 320);
    lv_obj_set_height(ui_select, 240);
    lv_obj_set_align(ui_select, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_select, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DDS = lv_tabview_add_tab(ui_select, "DDS");
    lv_obj_clear_flag(ui_DDS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Fre_tag = lv_label_create(ui_DDS);
    lv_obj_set_width(ui_Fre_tag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fre_tag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fre_tag, -90);
    lv_obj_set_y(ui_Fre_tag, -65);
    lv_obj_set_align(ui_Fre_tag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fre_tag, "Fre");

    ui_Fre_Value = lv_spinbox_create(ui_DDS);
    lv_obj_set_width(ui_Fre_Value, 80);
    lv_obj_set_height(ui_Fre_Value, 35);
    lv_obj_set_x(ui_Fre_Value, -20);
    lv_obj_set_y(ui_Fre_Value, -65);
    lv_obj_set_align(ui_Fre_Value, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Fre_Value, 4, 3);
    lv_spinbox_set_range(ui_Fre_Value, 0, 9999);
    lv_spinbox_set_step(ui_Fre_Value, round(pow(10, 1 - 1)));

    ui_DDS_Fre_Range = lv_dropdown_create(ui_DDS);
    lv_dropdown_set_options(ui_DDS_Fre_Range, "MHz\nKHz\nHz");
    lv_obj_set_width(ui_DDS_Fre_Range, 80);
    lv_obj_set_height(ui_DDS_Fre_Range, 35);
    lv_obj_set_x(ui_DDS_Fre_Range, 70);
    lv_obj_set_y(ui_DDS_Fre_Range, -65);
    lv_obj_set_align(ui_DDS_Fre_Range, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DDS_Fre_Range, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DDS_Vol_Slider = lv_slider_create(ui_DDS);
    lv_slider_set_range(ui_DDS_Vol_Slider, 0, 4095);
    lv_obj_set_width(ui_DDS_Vol_Slider, 150);
    lv_obj_set_height(ui_DDS_Vol_Slider, 10);
    lv_obj_set_x(ui_DDS_Vol_Slider, 40);
    lv_obj_set_y(ui_DDS_Vol_Slider, 20);
    lv_obj_set_align(ui_DDS_Vol_Slider, LV_ALIGN_CENTER);

    ui_DDS_Vol = lv_label_create(ui_DDS);
    lv_obj_set_width(ui_DDS_Vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DDS_Vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DDS_Vol, -90);
    lv_obj_set_y(ui_DDS_Vol, 20);
    lv_obj_set_align(ui_DDS_Vol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DDS_Vol, "Vol:0");

    ui_DDS_Output_tag = lv_label_create(ui_DDS);
    lv_obj_set_width(ui_DDS_Output_tag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DDS_Output_tag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DDS_Output_tag, -70);
    lv_obj_set_y(ui_DDS_Output_tag, 80);
    lv_obj_set_align(ui_DDS_Output_tag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DDS_Output_tag, "Sweep");

    ui_Fre_Value_Add = lv_btn_create(ui_DDS);
    lv_obj_set_width(ui_Fre_Value_Add, 30);
    lv_obj_set_height(ui_Fre_Value_Add, 20);
    lv_obj_set_x(ui_Fre_Value_Add, -40);
    lv_obj_set_y(ui_Fre_Value_Add, -30);
    lv_obj_set_align(ui_Fre_Value_Add, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fre_Value_Add, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fre_Value_Add, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_add = lv_label_create(ui_Fre_Value_Add);
    lv_obj_set_width(ui_add, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_add, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_add, LV_ALIGN_CENTER);
    lv_label_set_text(ui_add, "+");

    ui_Fre_Value_Dec = lv_btn_create(ui_DDS);
    lv_obj_set_width(ui_Fre_Value_Dec, 30);
    lv_obj_set_height(ui_Fre_Value_Dec, 20);
    lv_obj_set_x(ui_Fre_Value_Dec, 0);
    lv_obj_set_y(ui_Fre_Value_Dec, -30);
    lv_obj_set_align(ui_Fre_Value_Dec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fre_Value_Dec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Fre_Value_Dec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dec = lv_label_create(ui_Fre_Value_Dec);
    lv_obj_set_width(ui_dec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dec, "-");

    ui_Sweep_Switch = lv_switch_create(ui_DDS);
    lv_obj_set_width(ui_Sweep_Switch, 40);
    lv_obj_set_height(ui_Sweep_Switch, 20);
    lv_obj_set_x(ui_Sweep_Switch, 70);
    lv_obj_set_y(ui_Sweep_Switch, 80);
    lv_obj_set_align(ui_Sweep_Switch, LV_ALIGN_CENTER);

    ui_Screen_Button = lv_btn_create(ui_DDS);
    lv_obj_set_width(ui_Screen_Button, 59);
    lv_obj_set_height(ui_Screen_Button, 33);
    lv_obj_set_x(ui_Screen_Button, -98);
    lv_obj_set_y(ui_Screen_Button, -99);
    lv_obj_set_align(ui_Screen_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ADC = lv_tabview_add_tab(ui_select, "ADC");
    lv_obj_clear_flag(ui_ADC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Measure_Button = lv_btn_create(ui_ADC);
    lv_obj_set_width(ui_Measure_Button, 60);
    lv_obj_set_height(ui_Measure_Button, 30);
    lv_obj_set_x(ui_Measure_Button, 56);
    lv_obj_set_y(ui_Measure_Button, -68);
    lv_obj_set_align(ui_Measure_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Measure_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Measure_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Measure_tag = lv_label_create(ui_ADC);
    lv_obj_set_width(ui_Measure_tag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Measure_tag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Measure_tag, -62);
    lv_obj_set_y(ui_Measure_tag, -69);
    lv_obj_set_align(ui_Measure_tag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Measure_tag, "Measure");

    ui_Wave_Show = lv_chart_create(ui_ADC);
    lv_obj_set_width(ui_Wave_Show, 200);
    lv_obj_set_height(ui_Wave_Show, 100);
    lv_obj_set_x(ui_Wave_Show, 19);
    lv_obj_set_y(ui_Wave_Show, 29);
    lv_obj_set_align(ui_Wave_Show, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Wave_Show, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Wave_Show, 256);
    lv_chart_set_range(ui_Wave_Show, LV_CHART_AXIS_PRIMARY_Y, 0, 4096);
    lv_chart_set_axis_tick(ui_Wave_Show, LV_CHART_AXIS_PRIMARY_X, 10, 5, 13, 2, true, 50);
    lv_chart_set_axis_tick(ui_Wave_Show, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Wave_Show, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_Wave_Show_series_1 = lv_chart_add_series(ui_Wave_Show, lv_color_hex(0x808080),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Wave_Show_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Wave_Show, ui_Wave_Show_series_1, ui_Wave_Show_series_1_array);

    ui_DAC = lv_tabview_add_tab(ui_select, "DAC");
    lv_obj_clear_flag(ui_DAC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_DAC_Value_tag = lv_label_create(ui_DAC);
    lv_obj_set_width(ui_DAC_Value_tag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DAC_Value_tag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DAC_Value_tag, 0);
    lv_obj_set_y(ui_DAC_Value_tag, -30);
    lv_obj_set_align(ui_DAC_Value_tag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DAC_Value_tag, "DAC_Vol:0");

    ui_DAC_Value_Set = lv_slider_create(ui_DAC);
    lv_slider_set_range(ui_DAC_Value_Set, 0, 1240);
    lv_obj_set_width(ui_DAC_Value_Set, 150);
    lv_obj_set_height(ui_DAC_Value_Set, 10);
    lv_obj_set_x(ui_DAC_Value_Set, 0);
    lv_obj_set_y(ui_DAC_Value_Set, 15);
    lv_obj_set_align(ui_DAC_Value_Set, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Fre_Value, ui_event_Fre_Value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS_Fre_Range, ui_event_DDS_Fre_Range, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DDS_Vol_Slider, ui_event_DDS_Vol_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fre_Value_Add, ui_event_Fre_Value_Add, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fre_Value_Dec, ui_event_Fre_Value_Dec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sweep_Switch, ui_event_Sweep_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Button, ui_event_Screen_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Measure_Button, ui_event_Measure_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DAC_Value_Set, ui_event_DAC_Value_Set, LV_EVENT_ALL, NULL);

}
