// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: my_test

#ifndef _MY_TEST_UI_H
#define _MY_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void load_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_select;
extern lv_obj_t * ui_DAC;
extern lv_obj_t * ui_Wave_tab;
void ui_event_Wave_select(lv_event_t * e);
extern lv_obj_t * ui_Wave_select;
void ui_event_OUT_switch(lv_event_t * e);
extern lv_obj_t * ui_OUT_switch;
extern lv_obj_t * ui_OUT_tab;
extern lv_obj_t * ui_Fre_tab;
void ui_event_Fre(lv_event_t * e);
extern lv_obj_t * ui_Fre;
void ui_event_Fre_inc_btn(lv_event_t * e);
extern lv_obj_t * ui_Fre_inc_btn;
extern lv_obj_t * ui_Fre_inc_tab;
void ui_event_Fre_dec_btn(lv_event_t * e);
extern lv_obj_t * ui_Fre_dec_btn;
extern lv_obj_t * ui_Fre_dec_tab;
extern lv_obj_t * ui_Vol_tab;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_ADC;
extern lv_obj_t * ui_Label2;
void ui_event_measure(lv_event_t * e);
extern lv_obj_t * ui_measure;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
